// <auto-generated />
namespace Question2_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class MovieMigrations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MovieMigrations));
        
        string IMigrationMetadata.Id
        {
            get { return "202501021224215_MovieMigrations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
